### ISSUE TITLE
Multiplayer server crash on startup

### ISSUE THREAD

**Issue by Satrapie** [PhantomLoader/PhantomLoader#1] opened 2024-01-12 22:08 UTC
Hello, I just updated Underground Jungle (underground-jungle-forge-20.1.0.jar) for my multiplayer server, so I added the new dependencie, Phantom Loader (library-forge-20.1.4.jar), but now the server crashes on startup.

Here is the crash report :

[crash-2024-01-12_22.58.42-fml.txt](https://github.com/PhantomLoader/PhantomLoader/files/13924497/crash-2024-01-12_22.58.42-fml.txt)

**Comment by HexagonNico** [comment] 2024-01-20 11:36
I see the mod registry is trying to access the particles engine, which is only available in the client. Will try to fix that.

**Comment by HexagonNico** [comment] 2024-01-21 17:18
Fixed by 2584fbbba30ba0aaeb8818d477bed58b0ffbfc69

It was caused by Forge client events not being set to only be invoked on the client.

**Closed as completed by HexagonNico** 2024-01-21 17:18 UTC
Labels: bug
